import './models/product.dart';

final List<Product> products = [
  Product(
    title: 'Pullover',
    category: 'Top',
    price: 51,
    description: 'Mango',
    offerRate: 0,
    isFavorite: false,
    isNew: false,
    imgUrl: 'assets/images/winter-fashion-1.jpg',
  ),
  Product(
    title: 'Pullover1',
    category: 'Top',
    price: 51,
    description: 'Mango',
    offerRate: 0,
    isFavorite: false,
    isNew: false,
    imgUrl: 'assets/images/winter-fashion-1.jpg',
  ),
  Product(
    title: 'Pullover2',
    category: 'Top',
    price: 51,
    description: 'Mango',
    offerRate: 0,
    isFavorite: false,
    isNew: false,
    imgUrl: 'assets/images/winter-fashion-1.jpg',
  ),
  Product(
    title: 'Pullover3',
    category: 'Top',
    price: 51,
    description: 'Mango',
    offerRate: 0,
    isFavorite: false,
    isNew: false,
    imgUrl: 'assets/images/winter-fashion-1.jpg',
  ),
  Product(
    title: 'Pullover4',
    category: 'Top',
    price: 51,
    description: 'Mango',
    offerRate: 0,
    isFavorite: false,
    isNew: true,
    imgUrl: 'assets/images/winter-fashion-1.jpg',
  ),
  Product(
    title: 'Pullover5',
    category: 'Top',
    price: 51,
    description: 'Mango',
    offerRate: 0,
    isFavorite: true,
    isNew: false,
    imgUrl: 'assets/images/winter-fashion-1.jpg',
  ),
  Product(
    title: 'Pullover6',
    category: 'Top',
    price: 51,
    description: 'Mango',
    offerRate: 20,
    isFavorite: false,
    isNew: false,
    imgUrl: 'assets/images/winter-fashion-1.jpg',
  ),
  Product(
    title: 'Pullover7',
    category: 'Top',
    price: 51,
    description: 'Mango',
    offerRate: 0,
    isFavorite: false,
    isNew: false,
    imgUrl: 'assets/images/winter-fashion-1.jpg',
  ),
];
